name: Publish @enbiso/auth

on:
  push:
    branches:
      - main
    paths:
      - "projects/enbiso/auth/**"

jobs:
  build-web:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Packages
        run: npm i

      - name: Build
        run: ./build.sh utils-url rxjs-operators ngrx-route auth

      - name: Publish
        run: npm publish --access public
        working-directory: dist/enbiso/auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
