name: Publish @enbiso/rest-client

on:
  push:
    branches:
      - main
    paths:
      - "projects/enbiso/rest-client/**"

jobs:
  build-web:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Packages
        run: npm i

      - name: Build
        run: chmod +x ./build.sh && ./build.sh utils-url rxjs-operators ngrx-route auth rest-client

      - name: Publish
        run: npm publish --access public
        working-directory: dist/enbiso/rest-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
